### ISSUE TITLE
Do prplMesh have to be used with hostapd? What changes do I need to make to use prplMesh with MTK's private driver?

### ISSUE THREAD

**Issue by WeiXiaoQian** [prplfoundation/prplMesh-openwrt#5]
Do prplMesh have to be used with hostapd? What changes do I need to make to use prplMesh with MTK's private driver?

**Comment by wcloetens** [comment]
Short answer: yes.
Significant changes to hostapd are needed to support the EasyMesh Multi-AP protocol. These are being upstreamed to the hostap project as they are developed. In addition, a more dynamic interface to hostapd and wpa_supplicant (which is also required for backhaul links) is under development, not yet reflected in the current codebase.
The prplMesh project will only provide support for wireless drivers that adhere to the prpl Foundation Low-Level API recommendation, which mandates a fully functional cfg80211 driver without proprietary extensions.
MediaTek is fully aware of the prplMesh project. Feel free to reach out to them.
Alternatively, significant effort is being put in the open source mac80211 driver.

**Comment by WeiXiaoQian** [comment]
I truly appreciate your timely help.
